  client-id: ENC(Mk/1hPVxj7oMl6kcmk6O5/tEdMJDo/5qPkNrMeSqTpIBhut4CvGesdF6i3SK816i)
  redirect-local-uri: http://localhost:8080/auth/kakao
  redirect-uri: http://3.39.155.109:8080/auth/kakao
  kakao-token-url: https://kauth.kakao.com/oauth/token
  kakao-user-api-url: https://kapi.kakao.com/v2/user/me
  ALLOWED_ORIGIN: ENC(V+Pu7nR0W84LgxACczmHBTXU6krJMl0f09lJR0pAXjFvVISi4OYZXw==)